version: '3.8'

services:
  cursor-ultimate:
    build: .
    container_name: cursor-ultimate
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
